stages:
  feature-valuation:
    cmd: python -m mlrc22.experiments.feature_valuation_experiments
    deps:
    - src/mlrc22/experiments/feature_valuation_experiments.py
    outs:
    - output/feature_valuation/
  fixing-mislabeled-data:
    cmd: python -m mlrc22.experiments.fixing_mislabeled_data_experiment
    deps:
    - src/mlrc22/experiments/fixing_mislabeled_data_experiment.py
    outs:
    - output/fixing_mislabeled_data/
  noisy-data:
    cmd: python -m mlrc22.experiments.noisy_data_experiment
    deps:
    - src/mlrc22/experiments/noisy_data_experiment.py
    outs:
    - output/noisy_data/
  data-valuation-synthetic:
    cmd: python -m mlrc22.experiments.data_valuation_synthetic_experiment
    deps:
    - src/mlrc22/experiments/data_valuation_synthetic_experiment.py
    outs:
    - output/data_valuation_synthetic/
  data-valuation-dog-vs-fish:
    cmd: python -m mlrc22.experiments.data_valuation_dog_vs_fish_experiment
    deps:
    - src/mlrc22/experiments/data_valuation_dog_vs_fish_experiment.py
    outs:
    - output/data_valuation_dog_vs_fish/
